apiVersion: v1
kind: Service
metadata:
  name: unifi
  namespace: pve
spec:
  ports:
    - protocol: TCP
      port: 11443
      targetPort: 11443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: unifi
  namespace: pve
subsets:
  - addresses:
      - ip: 192.168.178.82
    ports:
      - port: 11443
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: unifi-router
  namespace: pve
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`unifi.attias.io`)
      kind: Rule
      services:
        - name: unifi
          port: 11443
      priority: 10
    #   middlewares:
    #     - name: authentik
    #       namespace: traefik
    # - kind: Rule
    #   match: "Host(`unifi.attias.io`) && PathPrefix(`/outpost.goauthentik.io/`)"
    #   priority: 15
    #   services:
    #       - kind: Service
    #         name: ak-outpost-authentik-embedded-outpost
    #         namespace: authentik
    #         port: 9000
  tls:
    certResolver: le