[Definition]
# This matches the remote_ip and the 401/403 status codes in Caddy's JSON
failregex = ^.*"remote_ip":"<HOST>".*"status":(?:401|403).*$

# Caddy uses a floating point Unix timestamp in the "ts" field
datepattern = "ts":<DATE>
